######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 17 09:34:01 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
